# Generated by Django 3.2.3 on 2021-05-31 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_report_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='user_fk',
            new_name='user',
        ),
    ]
