# Generated by Django 3.2.3 on 2021-06-02 12:50

from django.db import migrations, models
import core.models

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_image')
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='lat',
            field=models.DecimalField(max_digits=22, decimal_places=16, default=-6.200000),
        ),
        migrations.AlterField(
            model_name='report',
            name='long',
            field=models.DecimalField(max_digits=22, decimal_places=16, default=106.816666),
        ),
    ]
