# Generated by Django 3.2.3 on 2021-06-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_google_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.AddField(
            model_name='report',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='google_id',
            field=models.CharField(blank=True, default=None, max_length=22, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='user_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
