# Generated by Django 3.2.3 on 2021-06-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_damage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
